# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Perform EBMA using C++
#' @export
rCppEBMA <- function(x, y, weights, sd, tolerance) {
    .Call(`_ebmaRcpp_rCppEBMA`, x, y, weights, sd, tolerance)
}

#' Compute the adjusted weights
#' @export
wHat <- function(z) {
    .Call(`_ebmaRcpp_wHat`, z)
}

#' Compute the predicted z-values
#'
#' @export
zHat <- function(x, y, weights, sd) {
    .Call(`_ebmaRcpp_zHat`, x, y, weights, sd)
}

